#!/usr/bin/env php
<?php

require __DIR__ . "/vendor/autoload.php";

use App\Commands\Console\ClearCommand;
use App\Commands\Console\DBCommand;
use App\Commands\Console\DefaultCommand;
use App\Commands\Console\MakeCommand;
use App\Commands\Console\MigrateCommand;
use App\Commands\Console\ServeCommand;
use OSN\Framework\Console\App;

$app = new App(__DIR__);

$app->commander->register("migrate", MigrateCommand::class);
$app->commander->register("make", MakeCommand::class);
$app->commander->register("serve", ServeCommand::class);
$app->commander->register("clear", ClearCommand::class);
$app->commander->register("db", DBCommand::class);
$app->commander->registerDefault(DefaultCommand::class);

$app->run();
