#!/usr/bin/php
<?php

require __DIR__ . "/vendor/autoload.php";

use OSN\Framework\Commands\MakeCommand;
use OSN\Framework\Console\App;

$app = new App(__DIR__);
$app->commander->register(MakeCommand::class);
$app->run();
