# This is a basic workflow to help you get started with Actions

name: MySQL

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run the test script
        run: |
           sudo apt install mysql-community-server && sudo service mysql start && echo '' > ${{ github.workspace }}/storage/database2.sqlite && echo -e "DB_VENDOR = sqlite\nDB_NAME = ${{ github.workspace }}/storage/database2.sqlite" > ${{ github.workspace }}/.env && composer update && php ${{ github.workspace }}/console migrate
