# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run Composer Install
        run: composer update     
        
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.17.0
        with:
          php-version: 8.0

      # Runs a set of commands using the runners shell
      - name: Prepare project
        run: cp $GITHUB_WORKSPACE/.env.example .env && touch $GITHUB_WORKSPACE/storage/database.db && W=$(echo $GITHUB_WORKSPACE | sed 's/\//\\\//g') && (cat $GITHUB_WORKSPACE/.env | sed 's/DB_NAME \= .*/DB_NAME='$W'\/storage\/database\.db/') > $GITHUB_WORKSPACE/.env
         
      - name: Run migrations
        run: php console migrate
           
